### ISSUE TITLE
Not able to install python package

### ISSUE THREAD

**Issue by priyankaexp** [CamDavidsonPilon/tdigest#50]
**Environment**
Operating System: Mac OSX
Python Version: Python 3.5.4
How did you install tdigest: pip

**Error is:**
DELC02RC08VG8WN:tdigest-0.5.2.2 priyagupta$ pip3 install tdigest
Requirement already satisfied: tdigest in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tdigest-0.5.2.2-py3.5.egg (0.5.2.2)
Collecting accumulation_tree (from tdigest)
  Using cached https://files.pythonhosted.org/packages/e9/18/73c11ed9d379b5efea5cabcce4b53762ee4b0c3aea42bd944e992f8ee307/accumulation_tree-0.6.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    **ERROR: Download error on https://pypi.org/simple/cython/: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:719) -- Some packages may not be found!
    Couldn't find index page for 'cython' (maybe misspelled?)**
    Download error on https://pypi.org/simple/: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:719) -- Some packages may not be found!
    No local packages or working download links found for cython
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/bv/n02l1vdn6mn_rvn5hlq454mjgfm0_c/T/pip-install-jmrecmdu/accumulation-tree/setup.py", line 28, in <module>
        Extension('accumulation_tree.accumulation_tree', ['accumulation_tree/accumulation_tree.pyx'])
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/setuptools/__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/setuptools/dist.py", line 717, in fetch_build_eggs
        replace_conflicting=True,
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 782, in resolve
        replace_conflicting=replace_conflicting
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1077, in obtain
        return installer(requirement)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/setuptools/dist.py", line 784, in fetch_build_egg
        return cmd.easy_install(req)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 673, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('cython')
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/bv/n02l1vdn6mn_rvn5hlq454mjgfm0_c/T/pip-install-jmrecmdu/accumulation-tree/

**Comment by priyankaexp** [comment]
For now, I have installed  Cython as an independent package using
 pip3 install Cython 
and the installation worked fine after that.
